version: "2.7"


services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /home/michal/database/:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.dev
    command: python manage.py runserver  0.0.0.0:8080
    ports:
      - 8080:8080
    depends_on:
      - db

