services:
  web_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
    command: gunicorn  --workers=5 gifts_shaker.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000

