version: '2.7'


services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - ENV=prod
    command: >
      sh -c "python manage.py migrate &&
             gunicorn gifts_shaker.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on: 
      - db
volumes:
  postgres_data:
