version: '2.7'


services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py migrate &&
             gunicorn gifts_shaker.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on: 
      - db

volumes:
  postgres_data:
