# Generated by Django 4.1.3 on 2022-11-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifts',
            old_name='author',
            new_name='author_id',
        ),
    ]
