# Generated by Django 4.1.3 on 2022-11-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_rename_author_gifts_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
