# Generated by Django 4.1.3 on 2022-11-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_alter_gifts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='name',
            field=models.CharField(error_messages='zla wartosc', max_length=50, null=True),
        ),
    ]
