# Generated by Django 4.1.3 on 2022-11-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_alter_gifts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
