# Generated by Django 4.1.3 on 2022-11-27 15:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0005_alter_gifts_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaker_name', models.CharField(max_length=50, null=True)),
                ('group_members', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
