# Generated by Django 4.1.3 on 2022-11-29 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0007_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitations',
            name='shaker',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
