# Generated by Django 4.1.3 on 2022-12-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0011_delete_usershaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaker',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
