# Generated by Django 4.1.3 on 2022-12-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0012_shaker_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.IntegerField(null=True)),
                ('user_2', models.IntegerField(null=True)),
                ('shaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.shaker')),
            ],
        ),
    ]
