# Generated by Django 4.1.3 on 2022-12-15 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0013_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairs',
            name='user_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pairs',
            name='user_2',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
