# Generated by Django 4.1.3 on 2022-12-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0014_alter_pairs_user_1_alter_pairs_user_2'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pairs',
            constraint=models.UniqueConstraint(fields=('user_1', 'user_2', 'shaker'), name='unique_migration_host_combination'),
        ),
    ]
