# Generated by Django 4.1.3 on 2022-12-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0015_pairs_unique_migration_host_combination'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pairs',
            name='unique_migration_host_combination',
        ),
        migrations.AddConstraint(
            model_name='pairs',
            constraint=models.UniqueConstraint(fields=('user_1', 'shaker'), name='unique_migration_host_combination'),
        ),
    ]
