# Generated by Django 4.1.3 on 2022-12-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0017_swhaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Swhaker',
        ),
    ]
